"""
KnowledgeQuarry — Problem 02 Dashboard
Run after training: streamlit run kq_dashboard.py
Requires: training_results.json (generated by kq_solution.py)
"""

import json, random
import numpy as np
import streamlit as st
import plotly.graph_objects as go

st.set_page_config(page_title="KnowledgeQuarry · Problem 02", page_icon="🧠", layout="wide")

st.title("🧠 Learning Under Constraints")
st.caption("KnowledgeQuarry · Problem 02 · ML Engineering · Convoke 8.0 · DU CIC")
st.markdown("""
A Q-Learning agent controls two heterogeneous agents — a **Drone** and a **Ground Robot** — in a
10×10 warehouse grid. Tasks are randomly spawned each episode. The agent learns which agent to
activate and whether to pick up or deliver, improving measurably over 600 episodes.
""")

# ── LOAD DATA ────────────────────────────────────────────────────────────────

@st.cache_data
def load():
    try:
        with open("training_results.json") as f:
            return json.load(f)
    except FileNotFoundError:
        st.error("Run python kq_solution.py first to generate training_results.json")
        st.stop()

results = load()
qt = results["q_tasks"]
qr = results["q_rewards"]
rt = results["baseline_random_tasks"]
gt = results["baseline_greedy_tasks"]
ql = qt[-100:]

# ── TOP METRICS ──────────────────────────────────────────────────────────────

impr = (np.mean(ql) - np.mean(rt)) / max(np.mean(rt), 0.01) * 100
c1,c2,c3,c4,c5 = st.columns(5)
c1.metric("Q-agent (last 100 eps)", f"{np.mean(ql):.2f} tasks/ep", f"+{impr:.1f}% vs random")
c2.metric("Random baseline",  f"{np.mean(rt):.2f} tasks/ep")
c3.metric("Greedy baseline",  f"{np.mean(gt):.2f} tasks/ep")
c4.metric("Episodes trained", "600")
c5.metric("Max tasks/episode", "8")
st.divider()

# ── LEARNING CURVE ───────────────────────────────────────────────────────────

st.subheader("Learning curve — tasks completed per episode")

def smooth(data, w=30):
    return np.convolve(data, np.ones(w)/w, mode="valid").tolist()

fig_lc = go.Figure()
fig_lc.add_trace(go.Scatter(
    y=smooth(qt), name="Q-agent (smoothed w=30)",
    line=dict(color="#378ADD", width=2.5),
    fill="tozeroy", fillcolor="rgba(55,138,221,0.07)"
))
fig_lc.add_hline(y=np.mean(rt), line_dash="dash", line_color="#E24B4A",
    annotation_text=f"Random: {np.mean(rt):.2f}", annotation_position="right")
fig_lc.add_hline(y=np.mean(gt), line_dash="dash", line_color="#EF9F27",
    annotation_text=f"Greedy: {np.mean(gt):.2f}", annotation_position="right")
fig_lc.update_layout(height=320, margin=dict(l=40,r=120,t=20,b=40),
    xaxis_title="Episode", yaxis_title="Tasks completed",
    plot_bgcolor="white", paper_bgcolor="white")
fig_lc.update_xaxes(showgrid=True, gridcolor="#f0f0f0")
fig_lc.update_yaxes(showgrid=True, gridcolor="#f0f0f0")
st.plotly_chart(fig_lc, use_container_width=True)

# ── REWARD + EPSILON ─────────────────────────────────────────────────────────

ca, cb = st.columns(2)
with ca:
    st.subheader("Episode reward")
    fig_r = go.Figure(go.Scatter(
        y=smooth(qr), line=dict(color="#1D9E75", width=2),
        fill="tozeroy", fillcolor="rgba(29,158,117,0.07)"
    ))
    fig_r.update_layout(height=260, margin=dict(l=40,r=20,t=10,b=40),
        xaxis_title="Episode", yaxis_title="Reward",
        plot_bgcolor="white", paper_bgcolor="white")
    st.plotly_chart(fig_r, use_container_width=True)

with cb:
    st.subheader("Epsilon decay")
    fig_e = go.Figure(go.Scatter(
        y=results["epsilon"], line=dict(color="#7F77DD", width=2),
        fill="tozeroy", fillcolor="rgba(127,119,221,0.07)"
    ))
    fig_e.add_hline(y=0.05, line_dash="dot", line_color="#aaa",
        annotation_text="min ε = 0.05")
    fig_e.update_layout(height=260, margin=dict(l=40,r=20,t=10,b=40),
        xaxis_title="Episode", yaxis_title="Epsilon",
        plot_bgcolor="white", paper_bgcolor="white")
    st.plotly_chart(fig_e, use_container_width=True)

# ── COMPARISON BAR ───────────────────────────────────────────────────────────

st.subheader("Method comparison")
fig_bar = go.Figure(go.Bar(
    x=["Random", "Greedy", "Q-agent (last 100 eps)"],
    y=[np.mean(rt), np.mean(gt), np.mean(ql)],
    error_y=dict(type="data", array=[np.std(rt), np.std(gt), np.std(ql)], visible=True),
    marker_color=["#E24B4A","#EF9F27","#378ADD"],
    text=[f"{np.mean(rt):.2f}", f"{np.mean(gt):.2f}", f"{np.mean(ql):.2f}"],
    textposition="outside", width=0.4,
))
fig_bar.update_layout(height=300, margin=dict(l=40,r=40,t=20,b=40),
    yaxis=dict(title="Tasks completed", range=[0, 9]),
    plot_bgcolor="white", paper_bgcolor="white")
fig_bar.update_yaxes(showgrid=True, gridcolor="#f0f0f0")
st.plotly_chart(fig_bar, use_container_width=True)

st.divider()

# ── LIVE GRID VISUALISATION ──────────────────────────────────────────────────

st.subheader("Episode grid — agent positions, tasks, and depot")
st.caption("Shows a live simulated episode. Drone starts at (0,0), Robot at (9,9). Tasks spawn randomly. All agents move toward tasks and then return to the depot at (5,5).")

GRID = 10
DEPOT_POS = (5, 5)
N_TASKS = 8

if "seed" not in st.session_state:
    st.session_state.seed = 42

def simulate_episode(seed):
    random.seed(seed)
    taken = {(0,0),(9,9),DEPOT_POS}
    task_positions = []
    while len(task_positions) < N_TASKS:
        p = (random.randint(0,9), random.randint(0,9))
        if p not in taken:
            taken.add(p); task_positions.append(p)

    # Simulate simple greedy movement for visualisation
    drone = {"x":0,"y":0,"energy":40,"cargo":[],"path":[(0,0)]}
    robot = {"x":9,"y":9,"energy":120,"cargo":[],"path":[(9,9)]}
    tasks = [{"x":x,"y":y,"done":False,"assigned":False} for x,y in task_positions]

    def nearest(agent, tasks):
        free = [t for t in tasks if not t["assigned"] and not t["done"]]
        if not free: return None
        return min(free, key=lambda t: abs(agent["x"]-t["x"])+abs(agent["y"]-t["y"]))

    def move(agent, tx, ty, speed, energy_cost=1):
        for _ in range(speed):
            if agent["energy"] <= 0: break
            if agent["x"]==tx and agent["y"]==ty: break
            if abs(agent["x"]-tx) >= abs(agent["y"]-ty):
                agent["x"] += 1 if tx>agent["x"] else -1
            else:
                agent["y"] += 1 if ty>agent["y"] else -1
            agent["energy"] -= energy_cost
            agent["path"].append((agent["x"], agent["y"]))

    for _ in range(60):
        # drone: pick up if space, else go depot
        if drone["energy"] > 0:
            if len(drone["cargo"]) < 3:
                t = nearest(drone, tasks)
                if t:
                    t["assigned"] = True
                    move(drone, t["x"], t["y"], 2)
                    if drone["x"]==t["x"] and drone["y"]==t["y"]:
                        drone["cargo"].append(t)
                else:
                    move(drone, *DEPOT_POS, 2)
            else:
                move(drone, *DEPOT_POS, 2)
                if drone["x"]==DEPOT_POS[0] and drone["y"]==DEPOT_POS[1]:
                    for t in drone["cargo"]: t["done"]=True
                    drone["cargo"]=[]

        if robot["energy"] > 0:
            if len(robot["cargo"]) < 6:
                t = nearest(robot, tasks)
                if t:
                    t["assigned"] = True
                    move(robot, t["x"], t["y"], 1)
                    if robot["x"]==t["x"] and robot["y"]==t["y"]:
                        robot["cargo"].append(t)
                else:
                    move(robot, *DEPOT_POS, 1)
            else:
                move(robot, *DEPOT_POS, 1)
                if robot["x"]==DEPOT_POS[0] and robot["y"]==DEPOT_POS[1]:
                    for t in robot["cargo"]: t["done"]=True
                    robot["cargo"]=[]

        if all(t["done"] for t in tasks): break

    return drone, robot, tasks

drone_sim, robot_sim, tasks_sim = simulate_episode(st.session_state.seed)

fig_grid = go.Figure()

# Grid lines
for i in range(GRID+1):
    fig_grid.add_shape(type="line", x0=i,y0=0,x1=i,y1=GRID, line=dict(color="#e8e8e8",width=0.5))
    fig_grid.add_shape(type="line", x0=0,y0=i,x1=GRID,y1=i, line=dict(color="#e8e8e8",width=0.5))

# Task paths (faint)
for i, (x,y) in enumerate(drone_sim["path"][::3]):
    if i > 0:
        px, py = drone_sim["path"][max(0,(i-1)*3)]
        fig_grid.add_shape(type="line", x0=px+0.5,y0=py+0.5,x1=x+0.5,y1=y+0.5,
            line=dict(color="#378ADD", width=1, dash="dot"))

for i, (x,y) in enumerate(robot_sim["path"][::3]):
    if i > 0:
        px, py = robot_sim["path"][max(0,(i-1)*3)]
        fig_grid.add_shape(type="line", x0=px+0.5,y0=py+0.5,x1=x+0.5,y1=y+0.5,
            line=dict(color="#534AB7", width=1, dash="dot"))

# Completed tasks
done_tasks   = [t for t in tasks_sim if t["done"]]
undone_tasks = [t for t in tasks_sim if not t["done"]]

if done_tasks:
    fig_grid.add_trace(go.Scatter(
        x=[t["x"]+0.5 for t in done_tasks],
        y=[t["y"]+0.5 for t in done_tasks],
        mode="markers", name="Task (delivered)",
        marker=dict(size=14, color="#1D9E75", symbol="circle",
                    line=dict(color="white",width=1.5))
    ))

if undone_tasks:
    fig_grid.add_trace(go.Scatter(
        x=[t["x"]+0.5 for t in undone_tasks],
        y=[t["y"]+0.5 for t in undone_tasks],
        mode="markers", name="Task (pending)",
        marker=dict(size=14, color="#EF9F27", symbol="circle",
                    line=dict(color="white",width=1.5))
    ))

# Depot
fig_grid.add_trace(go.Scatter(
    x=[DEPOT_POS[0]+0.5], y=[DEPOT_POS[1]+0.5],
    mode="markers+text", name="Depot",
    text=["Depot"], textposition="top center",
    textfont=dict(size=11, color="#1D9E75"),
    marker=dict(size=22, color="#1D9E75", symbol="square",
                line=dict(color="white",width=2))
))

# Drone final position
fig_grid.add_trace(go.Scatter(
    x=[drone_sim["x"]+0.5], y=[drone_sim["y"]+0.5],
    mode="markers+text", name=f"Drone (energy={drone_sim['energy']})",
    text=["Drone"], textposition="top center",
    textfont=dict(size=11, color="#0C447C"),
    marker=dict(size=20, color="#378ADD", symbol="triangle-up",
                line=dict(color="white",width=2))
))

# Robot final position
fig_grid.add_trace(go.Scatter(
    x=[robot_sim["x"]+0.5], y=[robot_sim["y"]+0.5],
    mode="markers+text", name=f"Robot (energy={robot_sim['energy']})",
    text=["Robot"], textposition="top center",
    textfont=dict(size=11, color="#3C3489"),
    marker=dict(size=20, color="#534AB7", symbol="square",
                line=dict(color="white",width=2))
))

# Start positions
fig_grid.add_trace(go.Scatter(
    x=[0.5, 9.5], y=[0.5, 9.5],
    mode="markers", name="Start positions",
    marker=dict(size=8, color="gray", symbol="circle-open", line=dict(width=1.5))
))

delivered = sum(1 for t in tasks_sim if t["done"])
fig_grid.update_layout(
    height=500,
    margin=dict(l=20,r=20,t=40,b=20),
    title=f"Simulated episode — {delivered}/{N_TASKS} tasks delivered  |  Drone path (blue dashes) · Robot path (purple dashes)",
    xaxis=dict(range=[0,GRID], showticklabels=False, showgrid=False),
    yaxis=dict(range=[0,GRID], showticklabels=False, showgrid=False, scaleanchor="x"),
    plot_bgcolor="#fafafa", paper_bgcolor="white",
    legend=dict(x=1.01, y=0.99, font=dict(size=11)),
)
st.plotly_chart(fig_grid, use_container_width=True)

col1, col2, col3 = st.columns(3)
col1.metric("Tasks delivered", f"{delivered}/{N_TASKS}")
col2.metric("Drone energy remaining", f"{drone_sim['energy']}/40 steps")
col3.metric("Robot energy remaining", f"{robot_sim['energy']}/120 steps")

if st.button("Randomize episode layout"):
    st.session_state.seed = random.randint(0, 9999)
    st.rerun()

st.divider()

# ── AGENT SPECS ──────────────────────────────────────────────────────────────

st.subheader("Agent specifications")
c1, c2 = st.columns(2)
with c1:
    st.markdown("**Drone**")
    st.table({"Property":["Speed","Capacity","Battery","Start"],"Value":["2 cells/step","3 tasks","40 steps","(0, 0)"]})
with c2:
    st.markdown("**Ground Robot**")
    st.table({"Property":["Speed","Capacity","Energy","Start"],"Value":["1 cell/step","6 tasks","120 steps","(9, 9)"]})

# ── ACTIONS + REWARD ─────────────────────────────────────────────────────────

st.subheader("Action space & reward function")
c1, c2 = st.columns(2)
with c1:
    st.markdown("**4 actions the Q-agent chooses from:**")
    st.table({
        "Action":["0","1","2","3"],
        "Description":["Drone → pick up nearest task","Robot → pick up nearest task",
                        "Drone → go to depot (deliver)","Robot → go to depot (deliver)"]
    })
with c2:
    st.markdown("**Reward function:**")
    st.table({
        "Event":["Task delivered to depot","Task picked up","Each movement step","Agent exhausted with cargo"],
        "Reward":["+15","+3","−0.2","−25"]
    })

with st.expander("Methodology & assumptions"):
    st.markdown("""
    **State space** (7-dimensional discretised tuple):
    `(tasks_remaining//2, drone_energy_bucket, robot_energy_bucket, drone_cargo, robot_cargo, drone_dist_bucket, robot_dist_bucket)`

    **Hyperparameters:** lr=0.15, γ=0.95, ε-start=1.0, ε-min=0.05, ε-decay=0.992

    **Baselines:**
    - Random: uniform random action each step
    - Greedy: hand-coded rule — pick up if space available, deliver if full

    **Key design decision:** Actions are direct movement commands (not abstract strategies),
    so every action has an immediate, measurable effect and reward flows back every step.
    This is what allows the Q-table to converge within 600 episodes.
    """)

st.caption("KnowledgeQuarry · Convoke 8.0 · Cluster Innovation Centre, University of Delhi")